### PR TITLE
Update current website 

### PR DESCRIPTION
**Pull request by snehasi**
As a part of preparation for the customer survey, I've generated an updated new user website, documenting Bugmark's features. It's using Jekyll's minima theme and off-the-shelf Bootstrap4. The design has been created for a minimalistic, and clean experience.

- A responsive website, adapts to small screens.

- Explanation of what Bugmark is

- Use cases for Bugmark

- A section that explains how Bugmark works internally

- A comparison section of Bugmark with other market types

Content can be added/edited by anyone through markdown support in Jekyll. Everyone is welcome to do this! :)

Media content will be added, in future as they are finalised.

### CODE REVIEW

**Comment by snehasi** [comment]
The website is at present live [here](http://52.66.30.67:4000).

**Comment by snehasi** [comment]
The website can be viewed [here](http://52.66.30.67:4000) at present.

**Comment by andyl** [comment]
Thank you Sneha.

**Comment by snehasi** [comment]
Hi @andyl, thanks!
The Github pages link( https://bugmark.github.io/website/ ) is still pointing to the older version of the website. Could you please fix that, so that we can host it on gh pages?

**Comment by andyl** [comment]
@snehasi I had some difficulty merging your PR and have manually copied your home-page edits into the live site.  When I return we can continue to merge your work into the live site.

Live site now uses the new pages (https://bugmark.net).

Note that in our Github Pages configuration, we set it up to serve site pages out of the `docs` directory.

If you haven't: try setting up a repo which renders a live site.  I think that will help us to resolve our workflow issues.

**Comment by snehasi** [comment]
Thank you @andyl. I will set up the live site using gh pages in my fork of this repo on the branch master, docs dir and resolve the merge issues.

**Comment by snehasi** [comment]
Hi @andyl I've fixed the css rendering and generated the live site here : https://snehasi.github.io/website/
I've done it with the master branch in my fork, the merge conflicts are there as, the directory structure of my fork is completely different. I've included the notes in my fork as well, so shifting everything to the docs dir isn't necessary.

**Comment by snehasi** [comment]
There seems to be a problem with the gh pages server and the jekyll relative links, at times. Working on fixing it.

**Comment by snehasi** [comment]
Okay, fixed it.
https://snehasi.github.io/website/
@andyl can you please take a look?

**Comment by GeorgLink** [comment]
Thanks @snahasi.

It looks good. I made comments on the pull request.

**Pull request merged**
